### ISSUE TITLE
Dagre node use x y for node center rather than vertex coordinate

### ISSUE THREAD

**Issue by WangLeto** [xyflow/react-flow-docs#138]
The example code seems to behave incorrectly when there is difference in nodes size. Here's the link for example code:

https://github.com/wbkd/react-flow-docs/blob/fe57d8b54a21d8b1da0f0ba3c03b380f792ce758/src/components/CodeViewer/api-flows/LayoutingFlow2-Dagre/index.js#L28C35-L28C35

It should be like:

```
return { ...node, position: { x: x - node.width / 2, y: y - node.height / 2 } };
```

**Comment by WangLeto** [comment]
And this is Dagre doc: https://github.com/dagrejs/dagre/wiki#output-graph
<img width="717" alt="image" src="https://github.com/wbkd/react-flow-docs/assets/25009314/b52749ee-40ef-46f4-b47c-a59944e73488">

**Comment by chrtze** [comment]
Hey @WangLeto, thanks for the issue. This can probably be done with the [nodeOrigin prop](https://reactflow.dev/api-reference/react-flow#node-origin). We have a new docs site: https://github.com/xyflow/web. If this issue persists, please reopen in the new repo. Thank you!
