### ISSUE TITLE
Main page crashes 

### ISSUE THREAD

**Issue by chihabhajji** [xyflow/react-flow-docs#143]
![image](https://github.com/wbkd/react-flow-docs/assets/35853327/dbd5b300-7afa-438f-a5c3-066063b13e67)

Tried running project locally and on incognito, works fine, but crashes on https://reactflow.dev/ , i think the issue is related webgl not being loaded for the hero banner section animation

**Comment by chrtze** [comment]
we have a new docs site: https://github.com/xyflow/web. If this issue persists, please reopen in the new repo. Thank you!
