### ISSUE TITLE
Initialization issue In the Drag and Drop

### ISSUE THREAD

**Issue by nfplay** [xyflow/react-flow-docs#22]
Url: https://reactflow.dev/docs/examples/interaction/drag-and-drop/

If you remove the initial node in the example - that is, start without initial nodes deployed -, when you drag and drop the first node it will be dropped in the centered position instead of the position the user dropped it (it will be positioned as if it were the initial node of the example).

For this you only need to change `useNodesState(initialNodes)` to `useNodesState([])`. Looks like some initialization issue, any help is greatly appreciated.

Nuno

**Comment by moklick** [comment]
When you start with an empty node array you need to remove the `fitView` option. Otherwise the view will be fitted after you drop the first node (that's why it is centered).
