### ISSUE TITLE
Clarification on useReactFlow docs

### ISSUE THREAD

**Issue by stuarthallows** [xyflow/react-flow-docs#28]
The [code example for useReactFlow ](https://reactflow.dev/docs/examples/misc/use-react-flow-hook/) hook does not in fact use a hook called _useReactFlow_. Is the doc up to date?

**Comment by stuarthallows** [comment]
Ah, I missed the Sidebar.js link.

**Comment by moklick** [comment]
good point! `Sidebar.js` should be the active file now.
