### ISSUE TITLE
Broken example link in `getConnectedEdges()` of "Graph Util Functions"

### ISSUE THREAD

**Issue by AnsonH** [xyflow/react-flow-docs#49]
In ["Graph Utils Functions" -> `getConnectedEdges()`](https://github.com/wbkd/react-flow-docs/blob/main/docs/api/graph-util-functions.md?plain=1#L71), the "this example" link points to this dead link: https://github.com/wbkd/react-flow/blob/main/example/src/Overview/index.tsx#L100.

Is it possible to update the example link, if the example still exists? Thank you very much!

**Comment by chrtze** [comment]
I think this link should be at the bottom of the document here. It is not related to the getConnectedEdges function only but should mention an example for all the utility functions.

**Comment by chrtze** [comment]
Removed the comment for now, it was a leftover from older docs. The original link was this one: https://github.com/wbkd/react-flow/blob/v10/example/src/Overview/index.tsx#L100 but I don't really find it useful
